language: node_js
sudo: false
node_js:
  - "node"
install:
  - npm install -g mocha
  - npm install -g eslint
  - npm install
before_script:
  - mocha --version
  - eslint --version
script:
  - mocha
  - eslint .
